DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    MATRICULA INT NOT NULL
    );

DROP TABLE IF EXISTS DOMICILIOS;
CREATE TABLE DOMICILIOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CALLE VARCHAR(50) NOT NULL,
    NUMERO INT NOT NULL,
    LOCALIDAD VARCHAR(50) NOT NULL,
    PROVINCIA VARCHAR(50) NOT NULL
    );

DROP TABLE IF EXISTS PACIENTES;
CREATE TABLE PACIENTES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    DNI INT NOT NULL, FECHA DATE NOT NULL,
     DOMICILIO_ID INT
     );



 --Test--
    INSERT INTO ODONTOLOGOS (NOMBRE, APELLIDO, MATRICULA) VALUES ('Juan', 'Perez', 12345), ('Maria', 'Gomez', 54321);

    INSERT INTO DOMICILIOS(CALLE, NUMERO, LOCALIDAD, PROVINCIA) VALUES ('Av Colon', 32, 'CABA', 'Buenos Aires'), ('Calle Falsa', 2323, 'Nuevo Mexico', 'Mexico');

    INSERT INTO PACIENTES (NOMBRE, APELLIDO, DNI, FECHA, DOMICILIO_ID) VALUES ('Carlos', 'Perez', 16542358, '2024-02-24', 1), ('Azul', 'Violeta', 32451289, '2024-01-02', 2);
